### ISSUE TITLE
Game

### ISSUE THREAD

**Issue by Krupel** [guillaume-alves/Game#4]
-na classe name tens metodos a escrever na consola e não podes.
-o array do tabuleiro e o array de utilizadores tem de ser propriedades da classe Game não podem estar nos metodos

**Comment by guillaume-alves** [comment]
(o array do tabuleiro e o array de utilizadores tem de ser propriedades da classe Game não podem estar nos metodos)

Nesta forma ?

public Class Game {
- int nbRows, nbColumns;
- Animal [] [] gameTab;
- Player [] userTab;

**Comment by Krupel** [comment]
certo
